[SystemSettings]
######################################################################################################################################
# The R.E.A.L. VR mod internally disables Motion Blur and Dynamic Resolution Scaling for FF7R, as they don't work correctly in VR.   #
#                                                                                                                                    #
# It also allows you to add further custom options in this .ini file without the need for any third-party unlockers.                 #
#                                                                                                                                    #
# Be careful however that messing with the engine configuration could break VR support or lead to unexpected artifacts. Only modify  #
# this file if you know what you're doing, don't copy-paste dozens of random settings which you found on the Internet and which are  #
# supposed to "optimize" the game, and before asking for support make sure to remove all modifications that you made here.           #
######################################################################################################################################
